SERVER:
  #where flask should host ND
  HOST: 127.0.0.1
  PORT: 3301
  #where ND will be accessed
  ACCESS: http://127.0.0.1:3301/

EMAIL:
  USE_EMAIL: true
  USER: sender@example.com
  PASSWORD: password1
  RECEIVER_EMAIL: receiver@example.com
  SMTP_SERVER: smtp.gmail.com
  PORT: 465