#config for server
SERVER:
  #where flask should host ND
  HOST: 127.0.0.1
  PORT: 3301
  #where ND will be accessed
  ACCESS: http://127.0.0.1:3301/

#config for email alerts
EMAIL:
  USE_EMAIL: true
  #username for smtp server, generally just email address
  USER: sender@example.com
  PASSWORD: password1
  #email to send alerts to
  RECEIVER_EMAIL: receiver@example.com
  #smtp server information
  SMTP_SERVER: smtp.gmail.com
  PORT: 465

POSTGRES:
  HOST: 127.0.0.1
  PORT: 5432
  USERNAME: postgres
  PASSWORD: password1